### ISSUE TITLE
Errors with GHC 8.2.1

### ISSUE THREAD

**Issue by jtompuri** [BartMassey/genuine-sieve#1]
I ran into a couple of errors with GHC 8.2.1 that are easy to fix:

testPrime.hs, wheel.hs: 
- add "take" to "import Data.Set hiding (foldr, map, foldl')"

imperative-sieve.hs: 
- add "{-# LANGUAGE FlexibleContexts #-}" in the beginning of the file
- change "import Control.Monad.ST.Safe" to "import Control.Monad.ST"

**Comment by BartMassey** [comment]
Fixed. Thanks much!
