### ISSUE TITLE
OS X: "time" command doesn't have format option -f (bench.sh)  

### ISSUE THREAD

**Issue by jtompuri** [BartMassey/genuine-sieve#3]
Thank's for great Haskell examples! While trying out the new bench.sh script, I ran into a OS dependent issue: OS X's "time" command doesn't support format option "-f %e". Command "time -f %e" returns "-bash: -f: command not found".  "Time" command's default output on OS X is:
real	0m0.220s
user	0m0.211s
sys	0m0.006s

And with option "-p" (POSIX.2):
real 0.22
user 0.21
sys 0.00

**Comment by BartMassey** [comment]
Apparently MacOS X `bash` built-in `time` doesn't include formatting, and I'm guessing `/usr/bin/time` doesn't either. I've pushed a patch to use `/usr/bin/time` in POSIX mode: let me know if this works for you.
